apiVersion: v1
kind: Pod
metadata:
 name: config-pod
spec:
 containers:
  -name: config-pod
   image: nginx
   ports:
   - containerport: 80 
  env:
  - name: course
      valueFrom: 
      configMapKeyRef:
      name: devops-configdata
      key: course
  - name: trainer
      valueFrom:
      configMapKeyRef:
      name: devops-configdata
      key: trainer
  envFrom:
    - secretRef:
      name: secret-pod