apiVersion: v1
kind: Pod
metadata:
  name: nginx 
  labels:
   app: nginx
   demo: service
spec:
  # list of containers
  containers:
  - name: hnginx
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-service
spec:
 selector:
  app: nginx
  demo: service
 ports:
    - protocol: TCP
      port: 80 #serviceport
      targetPort: 80 #container/pod port
  